application: apsjobshistoricsearch
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /api/.*
  script: main.app

- url: /(.+)
  static_files: templates/\1
  upload: templates/.*

- url: /
  static_files: templates/index.html
  upload: templates/index\.html

libraries:
- name: webapp2
  version: "2.5.2"
